#
####################################
# Site Configurations
####################################
#
title: John Doe
description: My personal website.
preview-image: preview.png

#
####################################
# Page Settings
####################################
#
owner:
  name: John Doe
  bio: "currently drinking lactose-free milk"
  

#
####################################
# Handles and Links
####################################
#
links:
  email: johndoe@gmail.com
  github: johndoe
  linkedin: johndoe
  telegram: johndoe

#
####################################
# Timeline
####################################
#
timeline:
  job1:
    company: company_name
    title: position_title
    start: Mon. Year
    end: Mon. Year
    description: optional desc of work
  job2:
    company: company_name
    title: position_title
    start: Mon. Year
    end: Mon. Year
    description: optional desc of work