#
####################################
# Site Configurations
####################################
#
title: David Golding
description: David Green's Personal Website

#
####################################
# Page Settings
####################################
#
owner:
  name: David Goldberg
  bio: David Gorny is a software engineer interested in Supercell and Cake. He currently serves as a mentor for Gordan Ramsey, Gordan Ryan, and Dreek Ye.

#
####################################
# Handles and Links
####################################
#
links:
  email: davidgil@gmail.com
  github: https://github.com/davidgril/
  linkedin: https://www.linkedin.com/in/davidgern/
  telegram:
  twitter:
  blog: blog/

#
####################################
# Timeline
####################################
#
timeline:
  - job:
    company: Stealth Startup
    title: Founder, CEO, and CTO
    start: Oct. 2022
    end:
    description: Raising funding. Contact me for opportunities.
  - job:
    company: Columbia University
    title: PhD Student
    start: Sep. 2022
    end: Oct. 2022.
    description: Ascertained the laws of reality and the happenings of the universe.<br>Dropped out to reinvent quantum non-spatial technology.
  - job:
    company: Subway
    title: Cashier and Sub-Maker
    start: Sep. 2003
    end: Aug. 2022
    description: Worked with numbers to ensure customer satisfaction. Proved the Bounded Prime Gap conjecture while making subs.
  - job:
    company: Tesla
    title: Founder, CEO, and CTO
    start: July 2003
    end: Aug. 2003
    description: Invented electric vehicles and self-driving technology. Gave company to Elon Musk because I got bored.